### ISSUE TITLE
v3.1.7 release is backward incompatible

### ISSUE THREAD

**Issue by qsona** [phstc/shoryuken#423]
Hello, we are using shoryuken in production. Thank you very much for your great work.

Our app did not run after updating shoryuken from 3.1.6 to 3.1.7 due to this change https://github.com/phstc/shoryuken/pull/417/ because this PR included breaking changes, as the PR owner @atyndall mentioned.
So, would you please avoid to include breaking changes in the patch release? Or if you decide to use another rule, I'll obey it, like fixing the whole version in my Gemfile.

**Comment by phstc** [comment]
Hi @qsona 

After the changes in the PR, I thought it became backward compatible. The PR description isn't exactly how it ended being implemented. 

Anyway, I didn't mean to release a minor version with breaking changes. 

Could you give more details on the error you are facing? So I can work on another patch for adding backward compatibility.

**Comment by phstc** [comment]
> Our app did not run after updating shoryuken

@qsona could you send me the error? I would be happy to investigate to make it backwards compatible.

**Comment by qsona** [comment]
Sorry I jumped to a conclusion. I just judged by looking the PR description.

We are directly using `Shoryuken.add_group` and `Shoryuken.add_queue` instead of using yml when launching the shoryuken workers.

The problem occurred in here
https://github.com/appbot/shoryuken/blob/5cadf1b05e73edb35acc32843f652c8eba5562f4/lib/shoryuken/options.rb#L60
The specified group name wasn't `default`, so `options[:groups][group]` was evaluated and it failed because `options[:groups]` was nil.

Error log:
```
bundler: failed to load command: shoryuken
NoMethodError: undefined method `[]' for nil:NilClass
lib/shoryuken/options.rb:60:in `polling_strategy'
lib/shoryuken/launcher.rb:75:in `block in create_managers'
```

I created this issue because I thought the same problem might occur by using yml, but sorry I haven't digged it.

**Comment by phstc** [comment]
Ah, I think I found it.

I guess only by changing from [this](https://github.com/phstc/shoryuken/pull/417/files#diff-0b9d421fe41a37ac870420135cd57e7aR60) to :

```ruby
strategy = (
  group == 'default' ? options : options[:groups].to_h[group]
).to_h[:polling_strategy]
```

Would do. So it will fallback to the default, which is `WeightedRoundRobin`. 

WDYT?

**Comment by phstc** [comment]
But thinking more on it, not sure if `options[:groups]` should be nil, if the a group other than `default` was used.

**Comment by qsona** [comment]
Yes I think it makes sense, but I will run it with that change and report later. Thank you for your quick response.

**Comment by phstc** [comment]
@qsona let me know how it goes, I created a PR #423 which will make the compatibility with 3.1.6, despiting [this](https://github.com/phstc/shoryuken/issues/423#issuecomment-322518606).

**Comment by qsona** [comment]
@phstc Thank you, I confirmed it worked on our app.

**Comment by phstc** [comment]
Hi @qsona, thanks for helping with this! 3.1.8 is out with your fix.
