### ISSUE TITLE
undefined method `Hash' for MyWorker:Class

### ISSUE THREAD

**Issue by geekguy** [phstc/shoryuken#49]
https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/worker.rb#L40

This should be ```opts || {}``` , right ?

please correct me if I am wrong.

**Comment by geekguy** [comment]
Sorry, My bad. 

It doesn't work with ruby 1.9.x. These methods were introduced in ruby 2.x. 

Mind specifying this in readme ?

**Comment by phstc** [comment]
hm if you change it from `Hash(opts)` to `opts || {}` does it work on 1.9.x?  If yes, :+1: to make it compatible with 1.9.x? Could you give a try?

**Comment by geekguy** [comment]
```opts || {}``` works with 1.9.x.

but there are other issues with 1.9.x. 

like, Hash.to_h is also not defined in 1.9.x which is used at 3-4 places(at least).

**Comment by phstc** [comment]
I added a **Requirements** section on the README. Can you update to Ruby 2.0 or greater? Not sure if I will be able to make it compatible with 1.9 again.

**Comment by geekguy** [comment]
Works fine with 2.x. :)

**Comment by phstc** [comment]
Thanks :beers:
